### ISSUE TITLE
Review Data Scraping

### ISSUE THREAD

**Issue by jenyu7** [tmoi29/awkward_armadillos#1]
Ok y'all...
So we need to pass two hidden tags: 1) the movie title, 2) the url to its review
We can't just search for reviews after the user has clicked on the movie because the results may return more than one movie...and we don't want to display the reviews of other movies. 
We should just keep the url handy when we initially retrieve the search results (right now, we only take the movie title.) Then, we scrape the url (already retrieved) to display the review when the user clicks on the movie link in the search results. 
I've modified the nyt_process.py file to do this, but haven't tested it. The get_title() fxn has been renamed to search_results(), and it returns a list of lists, the sublists in this format: [movie_name, review_url]. 

Display the sublist[0] (movie name) and scrape sublist[1] (movie review.) Should be rather self-explanatory.

**Comment by tmoi29** [comment]
Tested it and should work now
